### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by danielruss** [episphere/donate#3]
From the epidonate paper:

```
For the convenience of applications relying on the popular script tag loading mechanism, a module loader is also available as <script src=”https://episphere.github.io/donate/donate.js”></script>.
```

there is no _donate.js_.  I think you should copy the correct js file to _donate.js_ so both the correct file and _donate.js_ exist.

**Comment by jonasalmeida** [comment]
Thank you Daniel: indeed the paper points to donate.js to assemble a quick *dona* SDK, which doesn't exist. The right file is donation.js. To fix it, I did as you suggested - copied donation.js into a new donate.js file so it works either way.
